version: "3"

services:

  proxy:
    container_name: static-website-proxy
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static-site-1:/srv/static-site-1
      - ./static-site-2:/srv/static-site-2
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  
volumes:
  caddy_data:
  caddy_config:

